spring:
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/railsuite

  flyway:
    enabled: true

server:
  port: 8080