services:
  postgres:
    image: postgres:16
    container_name: railsuite-postgres
    environment:
      POSTGRES_DB: railsuite
      POSTGRES_USER: railsuite_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  core:
    build:
      context: ../../backend/core
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/railsuite
      DB_USER: railsuite_user
      DB_PASSWORD: secret
    depends_on:
      - postgres