apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsuite-core
  namespace: railsuite
spec:
  replicas: 2

  selector:
    matchLabels:
      app: railsuite-core

  template:
    metadata:
      labels:
        app: railsuite-core

    spec:
      containers:
        - name: railsuite-core
          image: ghcr.io/tim16227/railsuite-core:latest

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/railsuite

            - name: SPRING_DATASOURCE_USERNAME
              value: railsuite_user

            - name: SPRING_DATASOURCE_PASSWORD
              value: secret