apiVersion: apps/v1
kind: Deployment
metadata:
  name: canteen-core
  namespace: railsuite
spec:
  replicas: 2

  selector:
    matchLabels:
      app: canteen-core

  template:
    metadata:
      labels:
        app: canteen-core

    spec:
      containers:
        - name: canteen-core
          image: ghcr.io/tim16227/canteen-core:latest

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/canteen

            - name: SPRING_DATASOURCE_USERNAME
              value: canteen_user

            - name: SPRING_DATASOURCE_PASSWORD
              value: secret