apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: railsuite

data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS keycloak;

    GRANT ALL PRIVILEGES
    ON SCHEMA keycloak
    TO canteen_user;