name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tim16227/canteen-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build & Push Frontend Image
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/tim16227/canteen-frontend:latest
            ghcr.io/tim16227/canteen-frontend:${{ github.sha }}